-- Run this in the Supabase SQL Editor to create the table correctly

CREATE TABLE sensor_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  device_id TEXT NOT NULL,
  sensor TEXT NOT NULL,
  temperature NUMERIC NOT NULL,
  humidity NUMERIC NOT NULL
);

-- Index to make querying by device and time faster for the dashboard
CREATE INDEX idx_sensor_readings_device_time ON sensor_readings(device_id, created_at DESC);
